SELECT 
    S.SUPP_NAME AS SupplierName,
    S.SUPP_CONTACT_NAME AS SupplierContactName,
    CONCAT(
        CASE 
            WHEN CHAR_LENGTH(S.SUPP_CONTACT_NUMBER) = 7 THEN CONCAT(SUBSTRING(S.SUPP_CONTACT_NUMBER, 1, 3), '-', SUBSTRING(S.SUPP_CONTACT_NUMBER, 4, 4))
            WHEN CHAR_LENGTH(S.SUPP_CONTACT_NUMBER) = 8 THEN CONCAT(SUBSTRING(S.SUPP_CONTACT_NUMBER, 1, 4), '-', SUBSTRING(S.SUPP_CONTACT_NUMBER, 5, 4))
            ELSE S.SUPP_CONTACT_NUMBER
        END
    ) AS SupplierContactNo1,
    '', -- No second contact number in the SUPPLIERS table
    COUNT(O.ORDER_ID) AS TotalOrders,
    FORMAT(SUM(O.TOTAL_AMOUNT), '##,###,###.00') AS OrderTotalAmount
FROM 
    SUPPLIERS S
LEFT JOIN 
    ORDERS O ON S.SUPP_ID = O.SUPP_ID
WHERE 
    O.ORDER_DATE BETWEEN '2022-01-01' AND '2022-08-31'
GROUP BY 
    S.SUPP_NAME, S.SUPP_CONTACT_NAME, S.SUPP_CONTACT_NUMBER;
