CREATE TABLE SUPPLIERS (
   SUPP_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   SUPP_NAME           VARCHAR2(2000),
   SUPP_CONTACT_NAME   VARCHAR2(2000),
   SUPP_ADDRESS        VARCHAR2(2000),
   SUPP_EMAIL          VARCHAR2(2000),
   SUPP_CONTACT_NUMBER VARCHAR2(2000)
);

INSERT INTO Suppliers (SUPP_NAME, SUPP_CONTACT_NAME,SUPP_ADDRESS,SUPP_EMAIL,SUPP_CONTACT_NUMBER)
SELECT 
    SUPPLIER_NAME, 		 
	 SUPP_CONTACT_NAME,  
	 SUPP_ADDRESS,
	 SUPP_EMAIL,
	 SUPP_CONTACT_NUMBER VARCHAR2 
FROM
    xxbcm_order_mgt;
    
    


CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    ORDER_REF VARCHAR(2000),
    ORDER_DATE DATE,
    SUPP_ID INT,
    TOTAL_AMOUNT VARCHAR(2000),
    DESCRIPTION VARCHAR(2000),
    STATUS VARCHAR(2000),
    FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIERS(SUPP_ID)
);

SET sql_mode = 'oracle';
INSERT INTO ORDERS (ORDER_REF,ORDER_DATE, SUPP_ID, TOTAL_AMOUNT, DESCRIPTION, STATUS)
SELECT 
    ORDER_REF,
    STR_TO_DATE(ORDER_DATE, '%d-%b-%Y'),
    (SELECT SUPP_ID FROM SUPPLIERS WHERE SUPPLIERS.SUPP_NAME = XXBCM_ORDER_MGT.SUPPLIER_NAME AND ROWNUM = '1'),
    ORDER_TOTAL_AMOUNT,
    ORDER_DESCRIPTION,
    ORDER_STATUS
    
FROM xxbcm_order_mgt;




CREATE TABLE ORDERS_ITEMS(
  ORDER_ITEMS_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  ORDER_ID INT,
  LINE_AMOUNT VARCHAR(2000), 
  FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
);


SET sql_mode = 'oracle';
INSERT INTO ORDERS_ITEMS (ORDER_ID,LINE_AMOUNT)
SELECT 
    (SELECT ORDER_ID FROM ORDERS WHERE orders.ORDER_REF = xxbcm_order_mgt.ORDER_REF AND ROWNUM = '1'),
    ORDER_LINE_AMOUNT
    
FROM xxbcm_order_mgt;




CREATE TABLE INVOICES (
    Invoice_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    Invoice_Ref VARCHAR2(2000),
    Invoice_Date DATE,
    Order_ID INT,
    Status VARCHAR2(2000),
    Hold_Reason VARCHAR2(2000),
    Amount VARCHAR(2000),
    Description VARCHAR2(2000),
    FOREIGN KEY (Order_ID) REFERENCES Orders(Order_ID)
);


SET sql_mode = 'oracle';
INSERT INTO INVOICES (Invoice_Ref,Invoice_Date,ORDER_ID,STATUS,HOLD_REASON,Amount,Description)
SELECT 
    INVOICE_REFERENCE,
    STR_TO_DATE(INVOICE_DATE, '%d-%b-%Y'),
    (SELECT ORDER_ID FROM ORDERS WHERE orders.ORDER_REF = xxbcm_order_mgt.ORDER_REF AND ROWNUM = '1'),
    INVOICE_STATUS,
    INVOICE_HOLD_REASON,
    INVOICE_AMOUNT,
    INVOICE_Description
    
FROM xxbcm_order_mgt;








    

 

 